//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.23 at 08:21:45 PM IST 
//


package com.bring.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bring.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bring.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsignmentSet.Consignment.PackageSet.Package.Width }
     * 
     */
    public ConsignmentSet.Consignment.PackageSet.Package.Width createConsignmentSetConsignmentPackageSetPackageWidth() {
        return new ConsignmentSet.Consignment.PackageSet.Package.Width();
    }

    /**
     * Create an instance of {@link ConsignmentSet.Consignment.PackageSet.Package }
     * 
     */
    public ConsignmentSet.Consignment.PackageSet.Package createConsignmentSetConsignmentPackageSetPackage() {
        return new ConsignmentSet.Consignment.PackageSet.Package();
    }

    /**
     * Create an instance of {@link ConsignmentSet.Consignment.PackageSet.Package.EventSet.Event }
     * 
     */
    public ConsignmentSet.Consignment.PackageSet.Package.EventSet.Event createConsignmentSetConsignmentPackageSetPackageEventSetEvent() {
        return new ConsignmentSet.Consignment.PackageSet.Package.EventSet.Event();
    }

    /**
     * Create an instance of {@link ConsignmentSet.Consignment.PackageSet.Package.Weight }
     * 
     */
    public ConsignmentSet.Consignment.PackageSet.Package.Weight createConsignmentSetConsignmentPackageSetPackageWeight() {
        return new ConsignmentSet.Consignment.PackageSet.Package.Weight();
    }

    /**
     * Create an instance of {@link ConsignmentSet.Consignment.TotalVolume }
     * 
     */
    public ConsignmentSet.Consignment.TotalVolume createConsignmentSetConsignmentTotalVolume() {
        return new ConsignmentSet.Consignment.TotalVolume();
    }

    /**
     * Create an instance of {@link ConsignmentSet.Consignment.PackageSet.Package.RecipientAddress }
     * 
     */
    public ConsignmentSet.Consignment.PackageSet.Package.RecipientAddress createConsignmentSetConsignmentPackageSetPackageRecipientAddress() {
        return new ConsignmentSet.Consignment.PackageSet.Package.RecipientAddress();
    }

    /**
     * Create an instance of {@link ConsignmentSet.Consignment.PackageSet.Package.EventSet.Event.RecipientSignature }
     * 
     */
    public ConsignmentSet.Consignment.PackageSet.Package.EventSet.Event.RecipientSignature createConsignmentSetConsignmentPackageSetPackageEventSetEventRecipientSignature() {
        return new ConsignmentSet.Consignment.PackageSet.Package.EventSet.Event.RecipientSignature();
    }

    /**
     * Create an instance of {@link ConsignmentSet.Consignment }
     * 
     */
    public ConsignmentSet.Consignment createConsignmentSetConsignment() {
        return new ConsignmentSet.Consignment();
    }

    /**
     * Create an instance of {@link ConsignmentSet.Consignment.PackageSet.Package.Height }
     * 
     */
    public ConsignmentSet.Consignment.PackageSet.Package.Height createConsignmentSetConsignmentPackageSetPackageHeight() {
        return new ConsignmentSet.Consignment.PackageSet.Package.Height();
    }

    /**
     * Create an instance of {@link ConsignmentSet.Consignment.TotalWeight }
     * 
     */
    public ConsignmentSet.Consignment.TotalWeight createConsignmentSetConsignmentTotalWeight() {
        return new ConsignmentSet.Consignment.TotalWeight();
    }

    /**
     * Create an instance of {@link ConsignmentSet }
     * 
     */
    public ConsignmentSet createConsignmentSet() {
        return new ConsignmentSet();
    }

    /**
     * Create an instance of {@link ConsignmentSet.Consignment.PackageSet.Package.EventSet }
     * 
     */
    public ConsignmentSet.Consignment.PackageSet.Package.EventSet createConsignmentSetConsignmentPackageSetPackageEventSet() {
        return new ConsignmentSet.Consignment.PackageSet.Package.EventSet();
    }

    /**
     * Create an instance of {@link ConsignmentSet.Consignment.PackageSet.Package.Length }
     * 
     */
    public ConsignmentSet.Consignment.PackageSet.Package.Length createConsignmentSetConsignmentPackageSetPackageLength() {
        return new ConsignmentSet.Consignment.PackageSet.Package.Length();
    }

    /**
     * Create an instance of {@link ConsignmentSet.Consignment.PackageSet.Package.Volume }
     * 
     */
    public ConsignmentSet.Consignment.PackageSet.Package.Volume createConsignmentSetConsignmentPackageSetPackageVolume() {
        return new ConsignmentSet.Consignment.PackageSet.Package.Volume();
    }

    /**
     * Create an instance of {@link ConsignmentSet.Consignment.PackageSet }
     * 
     */
    public ConsignmentSet.Consignment.PackageSet createConsignmentSetConsignmentPackageSet() {
        return new ConsignmentSet.Consignment.PackageSet();
    }

}
